### PR TITLE
docs: update README

### PR DESCRIPTION
**Pull request by vadasambar**
- fix typos

### CODE REVIEW

**Comment by vadasambar** [comment]
@suzuki-shunsuke,

**Comment by suzuki-shunsuke** [comment]
This isn't a pull request to [the upstream](https://github.com/suzuki-shunsuke/lambuild).

**Comment by vadasambar** [comment]
Mentioned you by mistake. My bad!

**Comment by suzuki-shunsuke** [comment]
I see. No problem.

**Pull request closed without merging**
